### PR TITLE
Add mlton basis file

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks! I just realized that `lcf` doesn't really depend on `cmlib`, only the standard basis library that comes with every SML distribution. I made the adjustment to the `.cm` file here: https://github.com/jonsterling/sml-lcf/commit/058bec0af7c0b3b4459d99c10915d7720aea0b09

~~~Could you rebase this on top of master and make the corresponding adjustment to the `.mlb` file? thanks!~~~

**Comment by jonsterling** [comment]
Actually, no need to rebase since there is no conflict, but you can remove the `cmlib` reference from there.

**Comment by ghost** [comment]
Okay, I went ahead and removed the `cmlib` reference.

**Comment by jonsterling** [comment]
thanks!

**Pull request merged**
